---
x-airflow-common:
  &airflow-common
  deploy:
    &airflow-common-deployment
    restart_policy:
      condition: on-failure
      delay: 30s
  environment:
    &airflow-common-environment
    AIRFLOW_FERNET_KEY: 46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
    AIRFLOW_SECRET_KEY: a25mQ1FHTUh3MnFRSk5KMEIyVVU2YmN0VGRyYTVXY08=
    AIRFLOW_EXECUTOR: CeleryExecutor
    AIRFLOW_DATABASE_NAME: airflow
    AIRFLOW_DATABASE_USERNAME: airflow
    AIRFLOW_DATABASE_PASSWORD: airflow_bitnami
    AIRFLOW_WEBSERVER_HOST: airflow
    AIRFLOW_LOAD_EXAMPLES: no
    AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
    AIRFLOW__CORE__DEFAULT_TIMEZONE: Asia/Ho_Chi_Minh
    AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE: Asia/Ho_Chi_Minh
  user: '${AIRFLOW_UID:-50000}:0'
  volumes:
    &airflow-common-volumes
    - ${PROJECT_DIR:-.}/dags:/opt/bitnami/airflow/dags
    - ${PROJECT_DIR:-.}/logs:/opt/bitnami/airflow/logs
    - ${PROJECT_DIR:-.}/plugins:/opt/bitnami/airflow/plugins
  depends_on:
    &airflow-common-dependencies
    postgresql:
      condition: service_healthy
    redis:
      condition: service_healthy

x-minio-common:
  &minio-common
  image: minio/minio:latest
  command: server --console-address ":9001" http://minio{1...4}/data{1...2}
  expose:
    - '9000'
    - '9001'
  environment:
    MINIO_ROOT_USER: minioadmin
    MINIO_ROOT_PASSWORD: minioadmin
  healthcheck:
    test: [ "CMD", "mc", "ready", "local" ]
    interval: 5s
    timeout: 5s
    retries: 5

version: '3.8'
services:
  postgresql:
    image: bitnami/postgresql:17.0.0-debian-12-r2
    environment:
      POSTGRESQL_DATABASE: airflow
      POSTGRESQL_USERNAME: airflow
      POSTGRESQL_PASSWORD: airflow_bitnami
    user: '0:0'
    ports:
      - '5432:5432'
    volumes:
      - ${PROJECT_DIR:-.}/data/postgresql:/bitnami/postgresql
    healthcheck:
      test: [ "CMD", "pg_isready", "-U" ,"$${POSTGRESQL_USERNAME}", "-d", "$${POSTGRESQL_DATABASE}" ]
      interval: 10s
      timeout: 30s
      retries: 50
  redis:
    image: bitnami/redis:6.2.16-debian-12-r0
    environment:
      ALLOW_EMPTY_PASSWORD: yes
    user: '0:0'
    ports:
      - '6379:6379'
    volumes:
      - ${PROJECT_DIR:-.}/data/redis:/bitnami/redis
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 30s
      retries: 50
  airflow-worker:
    <<: *airflow-common
    image: airflow-worker-rclone:2.10.2-debian-12-r0
    deploy:
      <<: *airflow-common-deployment
      replicas: 2
  airflow-scheduler:
    <<: *airflow-common
    image: bitnami/airflow-scheduler:2.10.2-debian-12-r0
  airflow:
    <<: *airflow-common
    image: bitnami/airflow:2.10.2-debian-12-r0
    ports:
      - '8080:8080'
    environment:
      <<: *airflow-common-environment
      AIRFLOW_PASSWORD: harry@2024
      AIRFLOW_USERNAME: harry
      AIRFLOW_EMAIL: harrytran001221@gmail.com
  sftp-server:
    image: sftp-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
      replicas: 2
    environment:
      SFTP_USERS: 'harry:harry@2024:1000:1000'

  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - ${PROJECT_DIR:-.}/data/minio/data1-1:/data1
      - ${PROJECT_DIR:-.}/data/minio/data1-2:/data2
  minio2:
    <<: *minio-common
    hostname: minio2
    volumes:
      - ${PROJECT_DIR:-.}/data/minio/data2-1:/data1
      - ${PROJECT_DIR:-.}/data/minio/data2-2:/data2
  minio3:
    <<: *minio-common
    hostname: minio3
    volumes:
      - ${PROJECT_DIR:-.}/data/minio/data3-1:/data1
      - ${PROJECT_DIR:-.}/data/minio/data3-2:/data2
  minio4:
    <<: *minio-common
    hostname: minio4
    volumes:
      - ${PROJECT_DIR:-.}/data/minio/data4-1:/data1
      - ${PROJECT_DIR:-.}/data/minio/data4-2:/data2
  minio:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ${PROJECT_DIR:-.}/minio/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4